version: '3.8'

services:
  web:
    build: .

    volumes:
      - .:/app  # Mount the current directory to /app in the container
    ports:
      - "8300:8000"
    command: >
      sh -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db  # Ensure db starts before web

  db:
    image: postgres:13  # Use a specific version of PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data
    environment:
      POSTGRES_DB: your_db_name         # Replace with your database name
      POSTGRES_USER: your_db_user       # Replace with your database user
      POSTGRES_PASSWORD: your_db_password  # Replace with your database password

volumes:
  postgres_data:  # Named volume for PostgreSQL data persistence
