# Generated by Django 5.1.1 on 2024-10-02 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look', models.IntegerField()),
                ('script', models.IntegerField()),
                ('acting', models.IntegerField()),
                ('soundtrack', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('overalscore', models.IntegerField()),
                ('description', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
