# Generated by Django 5.1.1 on 2024-10-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='theme',
            field=models.TextField(default=''),
        ),
    ]
