# Generated by Django 5.1.1 on 2024-10-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_director_alter_movie_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbID',
            field=models.TextField(default='tt0136397'),
            preserve_default=False,
        ),
    ]
