# Generated by Django 5.1.1 on 2024-10-06 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_imdbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='acted_movies', to='movies.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbRating',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
