# Generated by Django 5.1.1 on 2024-10-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_category_movie_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='writer',
            new_name='writers',
        ),
    ]
