# Generated by Django 5.1.1 on 2024-10-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_writer_movie_writers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(null=True, related_name='directed_movies', to='movies.person'),
        ),
    ]
